### PR TITLE
Req & Res Implementation

### PR DESCRIPTION
**Pull request by Sangyao42**

### CODE REVIEW

**Comment by Sangyao42** [comment]
I have finished the process and cgi logic. Please review it.
There are still two things I am waiting:
1. The class for Content-Type value. It might be a HeaderString or a HeaderStringVector
2. Parse the output from cgi. It should parse the "Content-Type=a value" separated from the content body.

**Comment by euns-kim** [comment]
I had some issue with git and merged my part to your branch. Hope it is fine. I will work elsewhere from now on.

**Comment by euns-kim** [comment]
can you update clt->path with the new file name when you successfully post a new file? I think I use it for the Content-Type and the file stat for Last-Modified. Or in case I have to query again for a new location block (? I don't think we have to tho)

**Comment by Sangyao42** [comment]
> can you update clt->path with the new file name when you successfully post a new file? I think I use it for the Content-Type and the file stat for Last-Modified. Or in case I have to query again for a new location block (? I don't think we have to tho)

I added a std::string location in the struct

**Comment by euns-kim** [comment]
Right now I am checking the file stat again in my function to get Last-Modified date. So I need the full path. I can build up the full path again, but it would be a bit redundant.

**Review by euns-kim — APPROVED** [review]
Looks good. Still did not understand what we do with the req body in cgi post request.

**Comment by euns-kim** [comment]
Would it be fine if i check cgi by checking if vector cgi_argv in the client struct is not empty? Or do you have any other suggestion?

**Comment by Sangyao42** [comment]
> Right now I am checking the file stat again in my function to get Last-Modified date. So I need the full path. I can build up the full path again, but it would be a bit redundant.

ok I will save the full path. but still in location. just don't want to messed up with requested path

**Comment by Sangyao42** [comment]
> Would it be fine if i check cgi by checking if vector cgi_argv in the client struct is not empty? Or do you have any other suggestion?

I think it is alright. And I will also add content-type and content-length for cgi in struct Client later

**Comment by Sangyao42** [comment]
> Looks good. Still did not understand what we do with the req body in cgi post request.

Right now, POST with CGI updates a file on server as one simple implementation

**Pull request merged**
